project:
  type: website
  output-dir: DOCS

website:
  title: "Rayan Awad Alim"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - Experience.qmd
      - Projects.qmd
      - Awards.qmd
      - Community.qmd
    

format:
  html:
    theme: minty
    css: styles.css
    toc: true

editor: visual

execute: 
  freeze: auto
  
